# Generated by Django 5.0.3 on 2024-03-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0003_recipe_delete_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="last_used",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
