# Generated by Django 5.0.3 on 2024-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0004_recipe_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="grain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="meat_alternate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
