# Generated by Django 5.0.3 on 2024-03-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0007_rename_ansnackrecipe_amsnackrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="ingredient1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amsnack_ingredient1",
                to="tottimeapp.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="ingredient2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amsnack_ingredient2",
                to="tottimeapp.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="ingredient3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amsnack_ingredient3",
                to="tottimeapp.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="ingredient4",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amsnack_ingredient4",
                to="tottimeapp.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="ingredient5",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amsnack_ingredient5",
                to="tottimeapp.inventory",
            ),
        ),
    ]
