# Generated by Django 5.0.3 on 2024-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0008_alter_amsnackrecipe_ingredient1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amsnackrecipe",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
