# Generated by Django 5.0.3 on 2024-03-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0009_alter_amsnackrecipe_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="ingredient1",
        ),
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="ingredient2",
        ),
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="ingredient3",
        ),
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="ingredient4",
        ),
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="ingredient5",
        ),
        migrations.RemoveField(
            model_name="pmsnackrecipe",
            name="user",
        ),
        migrations.DeleteModel(
            name="amSnackRecipe",
        ),
        migrations.DeleteModel(
            name="pmSnackRecipe",
        ),
    ]
