# Generated by Django 5.0.3 on 2024-03-27 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0011_breakfastrecipe_addfood_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PMRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("instructions", models.TextField(null=True)),
                ("qty1", models.PositiveIntegerField(null=True)),
                ("qty2", models.PositiveIntegerField(null=True)),
                ("qty3", models.PositiveIntegerField(null=True)),
                ("qty4", models.PositiveIntegerField(null=True)),
                ("qty5", models.PositiveIntegerField(null=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("fluid", models.CharField(blank=True, max_length=100, null=True)),
                ("fruit_veg", models.CharField(blank=True, max_length=100, null=True)),
                ("meat", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ingredient1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_ingredient1",
                        to="tottimeapp.inventory",
                    ),
                ),
                (
                    "ingredient2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_ingredient2",
                        to="tottimeapp.inventory",
                    ),
                ),
                (
                    "ingredient3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_ingredient3",
                        to="tottimeapp.inventory",
                    ),
                ),
                (
                    "ingredient4",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_ingredient4",
                        to="tottimeapp.inventory",
                    ),
                ),
                (
                    "ingredient5",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_ingredient5",
                        to="tottimeapp.inventory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
