# Generated by Django 5.0.3 on 2024-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0014_lastinventoryupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="resupply",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
