# Generated by Django 5.0.3 on 2024-04-19 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0018_alter_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
    ]
