# Generated by Django 5.0.3 on 2024-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0021_milkcount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="milkcount",
            old_name="qty",
            new_name="current_qty",
        ),
        migrations.AddField(
            model_name="milkcount",
            name="received_qty",
            field=models.IntegerField(default=0),
        ),
    ]
