# Generated by Django 5.0.3 on 2024-05-31 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0024_weeklymenu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.TextField()),
                (
                    "weekly_qty",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                        ]
                    ),
                ),
                ("daily", models.BooleanField(choices=[(True, "Yes"), (False, "No")])),
                (
                    "break_only",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
                (
                    "am_only",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
                (
                    "lunch_only",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
                (
                    "pm_only",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inventory",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.rule",
            ),
        ),
    ]
