# Generated by Django 5.0.3 on 2024-06-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0026_alter_inventory_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="amrecipe",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.rule",
            ),
        ),
        migrations.AddField(
            model_name="breakfastrecipe",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.rule",
            ),
        ),
        migrations.AddField(
            model_name="pmrecipe",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.rule",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.rule",
            ),
        ),
    ]
