# Generated by Django 5.0.3 on 2024-08-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0029_remove_orderlist_order_orderlist_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="category",
            field=models.CharField(
                choices=[
                    ("Meat", "Meat"),
                    ("Breakfast", "Breakfast"),
                    ("Snacks", "Snacks"),
                    ("Dairy", "Dairy"),
                    ("Fruits", "Fruits"),
                    ("Grains", "Grains"),
                    ("Vegetables", "Vegetables"),
                    ("Supplies", "Supplies"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="item",
            field=models.CharField(default="default_item", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
