# Generated by Django 5.0.3 on 2024-09-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0030_inventory_total_quantity_orderlist_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="units",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
