# Generated by Django 5.0.3 on 2024-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0036_mainuser_subuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subuser",
            name="user",
        ),
        migrations.AddField(
            model_name="subuser",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
