# Generated by Django 5.0.3 on 2024-10-30 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0037_remove_subuser_user_subuser_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subuser",
            name="user_id",
        ),
        migrations.AddField(
            model_name="subuser",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
