# Generated by Django 5.0.3 on 2024-11-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0038_remove_subuser_user_id_subuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="user",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
