# Generated by Django 5.0.3 on 2024-11-01 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0039_mainuser_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainuser",
            name="user",
        ),
    ]
