# Generated by Django 5.0.3 on 2024-11-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tottimeapp", "0040_remove_mainuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subusers",
                to="auth.group",
            ),
        ),
    ]
