# Generated by Django 5.0.3 on 2024-11-05 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0041_subuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subuser",
            old_name="role",
            new_name="group_id",
        ),
    ]
