# Generated by Django 5.0.3 on 2024-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0042_rename_role_subuser_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="yes_no_permission",
            field=models.BooleanField(default=False),
        ),
    ]
