# Generated by Django 5.0.3 on 2024-11-11 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0048_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
            to='tottimeapp.Conversation',
            on_delete=models.CASCADE,
            related_name='messages',
            null=True,  # Allow null initially
            ),
            preserve_default=False,
        ),
    ]
