# Generated by Django 5.0.3 on 2024-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0050_alter_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="stripe_public_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
