# Generated by Django 5.0.3 on 2024-11-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0052_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card"), ("cash", "Cash"), ("check", "Check")],
                default="card",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("partial_payment", "Partial Payment"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
