# Generated by Django 5.0.3 on 2024-11-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0053_payment_payment_method_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subuser",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subuser",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tottimeapp.student",
            ),
        ),
    ]
