# Generated by Django 5.0.3 on 2024-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0054_subuser_balance_subuser_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("minutely", "Minutely"),
                    ("yearly", "Yearly"),
                ],
                default="weekly",
                max_length=10,
            ),
        ),
    ]
