# Generated by Django 5.0.3 on 2024-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0055_payment_end_date_alter_payment_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="next_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
