# Generated by Django 5.0.3 on 2024-11-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0056_payment_next_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tottimeapp.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="weekly",
                max_length=10,
            ),
        ),
    ]
