# Generated by Django 5.0.3 on 2024-12-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0057_payment_student_alter_payment_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
