# Generated by Django 5.0.3 on 2024-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tottimeapp", "0059_mainuser_code_teacherattendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
