# Generated by Django 5.1.3 on 2025-02-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0061_alter_mainuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tottimeapp.classroom'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
