# Generated by Django 5.1.3 on 2025-02-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0063_classroom_ratios'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ratios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ratios', to='tottimeapp.classroom'),
        ),
    ]
