# Generated by Django 5.1.3 on 2025-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0064_attendancerecord_ratios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='ratios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
