# Generated by Django 5.1.3 on 2025-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0067_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='square_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='square_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='square_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
