# Generated by Django 5.1.3 on 2025-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0068_mainuser_square_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='square_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
