# Generated by Django 5.1.3 on 2025-04-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0069_mainuser_square_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('card', 'Card (Online)'), ('manual', 'Manual Entry'), ('balance', 'Balance Used'), ('refund', 'Refund Issued'), ('other', 'Other')], default='card', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='tottimeapp.subuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
