# Generated by Django 5.1.3 on 2025-04-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0070_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tuitions', to='tottimeapp.subuser')),
            ],
        ),
    ]
