# Generated by Django 4.2.20 on 2025-04-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0071_weeklytuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plans', to='tottimeapp.subuser')),
            ],
        ),
    ]
