# Generated by Django 4.2.20 on 2025-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0072_tuitionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytuition',
            name='has_been_charged',
            field=models.BooleanField(default=False),
        ),
    ]
