# Generated by Django 4.2.20 on 2025-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0073_weeklytuition_has_been_charged'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklytuition',
            unique_together={('subuser', 'start_date', 'end_date')},
        ),
    ]
