# Generated by Django 3.2.25 on 2025-04-14 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0074_alter_weeklytuition_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tottimeapp.subuser'),
        ),
    ]
