# Generated by Django 3.2.25 on 2025-04-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0075_auto_20250413_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_students', to='tottimeapp.subuser'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_students', to='tottimeapp.subuser'),
        ),
    ]
