# Generated by Django 3.2.25 on 2025-04-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0076_auto_20250415_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tottimeapp.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tottimeapp.subuser'),
        ),
    ]
