# Generated by Django 3.2.25 on 2025-04-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0077_auto_20250416_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='classroom',
        ),
        migrations.CreateModel(
            name='ClassroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tottimeapp.classroom')),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tottimeapp.subuser')),
            ],
        ),
    ]
