# Generated by Django 3.2.25 on 2025-04-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0078_auto_20250416_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classrooms', to='tottimeapp.subuser'),
        ),
    ]
