# Generated by Django 3.2.25 on 2025-04-17 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0079_classroom_assigned_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='assigned_teacher',
            new_name='assigned_teacher_subuser',
        ),
        migrations.AddField(
            model_name='classroom',
            name='assigned_teacher_mainuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classrooms_mainuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
