# Generated by Django 3.2.25 on 2025-04-17 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0080_auto_20250416_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomassignment',
            name='mainuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroomassignment',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tottimeapp.subuser'),
        ),
    ]
