# Generated by Django 3.2.25 on 2025-04-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0081_auto_20250417_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='assigned_teacher_mainuser',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='assigned_teacher_subuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='second_subuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subuser',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='student_pictures/default.jpg', null=True, upload_to='student_pictures/'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers', to='tottimeapp.student'),
        ),
    ]
