# Generated by Django 3.2.25 on 2025-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0082_auto_20250419_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom_override_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom_override_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom_override_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom_override_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp_override_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp_override_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp_override_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp_override_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
