# Generated by Django 3.2.25 on 2025-04-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tottimeapp', '0083_auto_20250423_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_message', models.BooleanField(default=False)),
                ('receiver_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_permissions', to='auth.group')),
                ('sender_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_permissions', to='auth.group')),
            ],
            options={
                'unique_together': {('sender_role', 'receiver_role')},
            },
        ),
    ]
