# Generated by Django 3.2.25 on 2025-04-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0084_messagingpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingpermission',
            name='main_user',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_permissions', to='tottimeapp.mainuser'),
            preserve_default=False,
        ),
    ]
