# Generated by Django 3.2.25 on 2025-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tottimeapp', '0085_messagingpermission_main_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagingpermission',
            unique_together={('main_user', 'sender_role', 'receiver_role')},
        ),
    ]
