# Generated by Django 3.2.25 on 2025-04-28 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0086_alter_messagingpermission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_account_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='main_account_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
