# Generated by Django 3.2.25 on 2025-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0088_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='student',
        ),
        migrations.AddField(
            model_name='subuser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='tottimeapp.Student'),
        ),
    ]
