# Generated by Django 3.2.25 on 2025-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0091_inventory_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
