# Generated by Django 3.2.21 on 2025-05-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0092_inventory_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='barcode_image',
        ),
    ]
