# Generated by Django 3.2.21 on 2025-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0094_usermessagingpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='color',
            field=models.CharField(default='#57bdb4', max_length=7),
        ),
    ]
