# Generated by Django 3.2.21 on 2025-06-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0095_classroom_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='student_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='student_pictures/default.png', null=True, upload_to='student_pictures/'),
        ),
    ]
