# Generated by Django 3.2.21 on 2025-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0097_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
