# Generated by Django 3.2.21 on 2025-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0098_announcement_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='parent_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
