# Generated by Django 3.2.21 on 2025-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0099_incidentreport_parent_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='parent_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
