# Generated by Django 3.2.21 on 2025-08-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0102_auto_20250806_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_owners', to='tottimeapp.company')),
                ('main_account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'main_account_owner')},
            },
        ),
    ]
