# Generated by Django 3.2.21 on 2025-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0103_companyaccountowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='can_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subuser',
            name='can_switch',
            field=models.BooleanField(default=False),
        ),
    ]
