# Generated by Django 3.2.21 on 2025-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0104_auto_20250806_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccountowner',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
