# Generated by Django 3.2.21 on 2025-08-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0105_companyaccountowner_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccountowner',
            name='facility_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='companyaccountowner',
            name='facility_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyaccountowner',
            name='facility_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyaccountowner',
            name='facility_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyaccountowner',
            name='facility_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
