# Generated by Django 3.2.21 on 2025-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0106_auto_20250818_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_middle_initial', models.CharField(blank=True, max_length=1)),
                ('child_nick_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('parent1_full_name', models.CharField(max_length=200)),
                ('parent1_home_phone', models.CharField(blank=True, max_length=20)),
                ('parent1_work_phone', models.CharField(blank=True, max_length=20)),
                ('parent1_other_phone', models.CharField(blank=True, max_length=20)),
                ('parent2_full_name', models.CharField(blank=True, max_length=200)),
                ('parent2_home_phone', models.CharField(blank=True, max_length=20)),
                ('parent2_work_phone', models.CharField(blank=True, max_length=20)),
                ('parent2_other_phone', models.CharField(blank=True, max_length=20)),
                ('form_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'enrollment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
