# Generated by Django 3.2.21 on 2025-08-20 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0107_enrollmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='Default Enrollment Form', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_title', models.CharField(default='South Carolina Department of Social Services', max_length=500)),
                ('header_subtitle', models.CharField(default='Child Care Regulatory Services', max_length=500)),
                ('form_title', models.CharField(default="GENERAL RECORD AND STATEMENT OF CHILD'S HEALTH FOR ADMISSION TO CHILD CARE FACILITY", max_length=500)),
                ('form_description', models.TextField(default='This form is to be completed for each child at the time of enrollment in the child care facility, updated as needed when changes occur, and maintained on file at the facility.')),
                ('footer_text', models.CharField(blank=True, default='DSS Form 2900 (MAR 10) Edition of OCT 07 is obsolete.', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_templates', to='tottimeapp.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_templates', to='tottimeapp.companyaccountowner')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'location', 'template_name')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('general_info', 'General Information'), ('health_info', 'Health Information'), ('pickup_info', 'Child Pick Up Information'), ('policies', 'Policies'), ('child_info', 'Child Information'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tottimeapp.enrollmenttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'section_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFormRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_classes', models.CharField(default='form-row', max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_rows', to='tottimeapp.enrollmentsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('email', 'Email Input'), ('tel', 'Phone Number'), ('date', 'Date'), ('time', 'Time'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('select', 'Dropdown'), ('signature', 'Signature Pad'), ('readonly', 'Read Only')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tottimeapp.enrollmentsection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'field_name')},
            },
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tottimeapp.enrollmenttemplate'),
        ),
        migrations.CreateModel(
            name='EnrollmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('emergency_medical', 'Emergency Medical'), ('after_school', 'After School Children'), ('summer_camp', 'Summer Camp'), ('abc_children', 'ABC Children'), ('transportation', 'Transportation'), ('biting', 'Biting Policy'), ('meals', 'Meals'), ('curriculum', 'Curriculum'), ('closings', 'Closings'), ('insurance', 'Insurance'), ('pictures', 'Pictures'), ('physical_activity', 'Physical Activity'), ('facility_agreement', 'Facility Agreement'), ('safety', 'Safety'), ('transitioning', 'Transitioning Policy'), ('naptime', 'Naptime'), ('potty', 'Using the Potty'), ('discipline', 'Discipline Policy'), ('disabilities', 'Disabilities'), ('ifsp_iep', 'IFSP/IEP'), ('hiring', 'Hiring Policy'), ('guidelines', 'General Guidelines'), ('pickup', 'Pick Up'), ('immunizations', 'Immunizations'), ('infants', 'Infants'), ('sickness', 'Sickness Policy'), ('hours', 'Days & Hours'), ('registration', 'Registration Fee'), ('rates', 'Rates'), ('payment', 'Payment Instructions'), ('dropbox', 'Drop Box'), ('dropoff', 'Drop Off'), ('belongings', 'Belongings'), ('custom', 'Custom Policy')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tottimeapp.enrollmenttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'policy_type', 'title')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tottimeapp.enrollmentfield')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_classes', models.CharField(default='form-group', max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='tottimeapp.enrollmentfield')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='tottimeapp.enrollmentformrow')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('row', 'field')},
            },
        ),
    ]
