# Generated by Django 3.2.21 on 2025-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0108_auto_20250820_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentfieldgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollmentfieldgroup',
            name='field',
        ),
        migrations.RemoveField(
            model_name='enrollmentfieldgroup',
            name='row',
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentfieldoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollmentfieldoption',
            name='field',
        ),
        migrations.RemoveField(
            model_name='enrollmentformrow',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollmentsection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='enrollmentsubmission',
            name='form_data',
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='attendance_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='child_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='child_street_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dental_care_provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dental_provider_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dental_provider_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dental_provider_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dropin_hours_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='dropin_hours_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_family_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency1_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_family_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency2_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency_care_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency_facility_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency_facility_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='emergency_facility_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='enrolled_in_school',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='facility_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='facility_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='facility_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='family_physician_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='fathers_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='fathers_employment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='health_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='health_insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='immunization_certificate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='immunization_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='meals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='mothers_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='mothers_employment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='mothers_ssn',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='parent_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='parent_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='physician_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='physician_city_state_zip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='physician_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_child_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_child_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_emergency1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_emergency1_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_emergency2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_emergency2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_father_cell',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_father_work',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_mother_cell',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_mother_work',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person1_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person3_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='pickup_person4_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='regular_hours_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='regular_hours_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='staff_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='staff_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EnrollmentField',
        ),
        migrations.DeleteModel(
            name='EnrollmentFieldGroup',
        ),
        migrations.DeleteModel(
            name='EnrollmentFieldOption',
        ),
        migrations.DeleteModel(
            name='EnrollmentFormRow',
        ),
        migrations.DeleteModel(
            name='EnrollmentSection',
        ),
    ]
