# Generated by Django 3.2.21 on 2025-08-21 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0109_auto_20250821_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttemplate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='enrollmentpolicy',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmenttemplate',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
