# Generated by Django 3.2.21 on 2025-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0110_auto_20250821_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentsubmission',
            name='processed',
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('enrolled', 'Enrolled'), ('archive', 'Archive')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='status_changed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='status_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
