# Generated by Django 3.2.21 on 2025-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0111_auto_20250825_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='parent2_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='parent2_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
