# Generated by Django 3.2.21 on 2025-09-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0112_auto_20250827_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
