# Generated by Django 3.2.21 on 2025-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0113_rolepermission_main_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentsubmission',
            name='photo_permission_parent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
