# Generated by Django 3.2.21 on 2025-09-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0114_enrollmentsubmission_photo_permission_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentpolicy',
            unique_together={('template', 'title')},
        ),
        migrations.RemoveField(
            model_name='enrollmentpolicy',
            name='policy_type',
        ),
    ]
