# Generated by Django 3.2.21 on 2025-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0116_orientationitem_orientationprogress_stafforientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafforientation',
            name='staff_member',
        ),
        migrations.AddField(
            model_name='stafforientation',
            name='staff_name',
            field=models.CharField(default='Unknown Staff', max_length=255),
        ),
    ]
