# Generated by Django 3.2.21 on 2025-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0117_auto_20250917_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientationprogress',
            name='initialed_text',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
