# Generated by Django 3.2.21 on 2025-09-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0118_orientationprogress_initialed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafforientation',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user_orientations', to=settings.AUTH_USER_MODEL),
        ),
    ]
