# Generated by Django 3.2.21 on 2025-09-22 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0119_stafforientation_main_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('age_range', models.CharField(max_length=100)),
                ('date_of_observation', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('teachers_initials', models.CharField(max_length=255)),
                ('assessor_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user_score_sheets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('letter', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user_standard_categories', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='StandardCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('points_available', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='tottimeapp.standardcategory')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottimeapp.standardcriteria')),
                ('score_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='tottimeapp.classroomscoresheet')),
            ],
            options={
                'unique_together': {('score_sheet', 'criteria')},
            },
        ),
    ]
