# Generated by Django 3.2.21 on 2025-09-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0121_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_public',
        ),
    ]
