# Generated by Django 3.2.21 on 2025-09-25 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0122_remove_resource_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ResourceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signature_data', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='tottimeapp.resource')),
            ],
        ),
    ]
