# Generated by Django 3.2.21 on 2025-09-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0123_auto_20250925_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardcategory',
            unique_together={('main_user', 'letter')},
        ),
    ]
