# Generated by Django 3.2.21 on 2025-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0124_alter_standardcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='indicator_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('general', 'General'), ('abc_quality', 'ABC Quality')], default='general', max_length=20),
        ),
    ]
