# Generated by Django 3.2.21 on 2025-10-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0125_auto_20251007_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCQualityElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('element_number', models.CharField(max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_section', models.BooleanField(default=False)),
                ('parent_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tottimeapp.abcqualityelement')),
            ],
            options={
                'ordering': ['display_order', 'element_number'],
            },
        ),
        migrations.CreateModel(
            name='ABCQualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('points', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='tottimeapp.abcqualityelement')),
            ],
            options={
                'ordering': ['display_order', 'indicator_id'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='abc_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='tottimeapp.abcqualityindicator'),
        ),
    ]
