# Generated by Django 3.2.21 on 2025-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0127_answer_choice_improvementgoal_improvementplan_question_response_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
