# Generated by Django 3.2.21 on 2025-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0129_publiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
