# Generated by Django 3.2.21 on 2025-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0130_publiclink_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiclink',
            name='is_preview',
        ),
    ]
