# Generated by Django 3.2.21 on 2025-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0131_remove_publiclink_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
