# Generated by Django 3.2.21 on 2025-10-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0132_publiclink_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_template', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='tottimeapp.abcqualityindicator')),
            ],
            options={
                'unique_together': {('indicator',)},
            },
        ),
    ]
