# Generated by Django 3.2.21 on 2025-10-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0133_indicatorpagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorpagelink',
            name='indicator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_link', to='tottimeapp.abcqualityindicator'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorpagelink',
            unique_together=set(),
        ),
    ]
