# Generated by Django 3.2.21 on 2025-10-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0134_auto_20251022_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('target_url', models.CharField(default='/abc-quality/', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
