# Generated by Django 3.2.21 on 2025-10-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0135_temporaryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorpagelink',
            name='main_user',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_page_links', to='tottimeapp.mainuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatorpagelink',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='tottimeapp.abcqualityindicator'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorpagelink',
            unique_together={('indicator', 'main_user')},
        ),
    ]
