# Generated by Django 3.2.21 on 2025-10-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0136_auto_20251024_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='main_user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='tottimeapp.mainuser'),
            preserve_default=False,
        ),
    ]
