# Generated by Django 3.2.21 on 2025-11-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0137_orderlist_main_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tottimeapp.classroom')),
            ],
            options={
                'unique_together': {('classroom', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tottimeapp.curriculumtheme')),
            ],
        ),
    ]
