# Generated by Django 3.2.21 on 2025-11-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0138_curriculumactivity_curriculumtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumactivity',
            name='main_user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_activities', to='tottimeapp.mainuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumtheme',
            name='main_user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_themes', to='tottimeapp.mainuser'),
            preserve_default=False,
        ),
    ]
