# Generated by Django 3.2.21 on 2025-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0139_auto_20251103_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumactivity',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='activity_pdfs/'),
        ),
    ]
