# Generated by Django 3.2.21 on 2025-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0140_curriculumactivity_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumactivity',
            name='date',
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
