# Generated by Django 3.2.21 on 2025-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0141_auto_20251103_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumactivity',
            name='pdf',
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='activity_files/'),
        ),
    ]
