# Generated by Django 3.2.21 on 2025-11-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0142_auto_20251103_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='main_user',
        ),
    ]
