# Generated by Django 3.2.21 on 2025-11-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0143_rename_user_student_main_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('formula_breast_milk', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_snack_cereal', models.CharField(blank=True, max_length=100, null=True)),
                ('fruit_vegetable', models.CharField(blank=True, max_length=100, null=True)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='tottimeapp.student')),
            ],
        ),
    ]
