# Generated by Django 3.2.21 on 2025-11-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0144_feedrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedrecord',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='feedrecord',
            name='formula_breast_milk',
        ),
        migrations.RemoveField(
            model_name='feedrecord',
            name='fruit_vegetable',
        ),
        migrations.RemoveField(
            model_name='feedrecord',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='feedrecord',
            name='meal_snack_cereal',
        ),
        migrations.RemoveField(
            model_name='feedrecord',
            name='snack',
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='meal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack')], default='mea', max_length=10),
            preserve_default=False,
        ),
    ]
