# Generated by Django 3.2.21 on 2025-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0145_auto_20251111_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrecord',
            name='ounces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
