# Generated by Django 3.2.21 on 2025-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0146_feedrecord_ounces'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='formula_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
