# Generated by Django 3.2.21 on 2025-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0147_student_formula_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='gradient_end',
            field=models.CharField(default='rgba(240,240,240,0.5)', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='gradient_start',
            field=models.CharField(default='rgba(200,200,200,0.3)', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='text_color',
            field=models.CharField(default='#333', max_length=50),
        ),
    ]
