# Generated by Django 3.2.21 on 2025-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0148_auto_20251215_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='meal_period',
            field=models.CharField(choices=[('all', 'All Meals'), ('breakfast', 'Breakfast'), ('am_snack', 'AM Snack'), ('lunch', 'Lunch'), ('pm_snack', 'PM Snack')], default='all', help_text='Specify when this item can be used in the menu', max_length=20),
        ),
    ]
