# Generated by Django 3.2.21 on 2026-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0150_auto_20251218_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='breakfastrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='fruitrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='pmrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='vegrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
        migrations.AddField(
            model_name='wgrecipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipe_pictures/'),
        ),
    ]
