# Generated by Django 3.2.21 on 2026-01-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0151_auto_20260107_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenuAssignedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tottimeapp.rule')),
                ('weekly_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rules', to='tottimeapp.weeklymenu')),
            ],
            options={
                'unique_together': {('weekly_menu', 'cell_id')},
            },
        ),
    ]
