# Generated by Django 3.2.21 on 2026-01-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0152_weeklymenuassignedrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenuassignedrule',
            name='manual_color_data',
            field=models.JSONField(blank=True, help_text='Manual color override data (if not using a Rule)', null=True),
        ),
        migrations.AlterField(
            model_name='weeklymenuassignedrule',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tottimeapp.rule'),
        ),
    ]
