# Generated by Django 3.2.21 on 2026-02-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tottimeapp', '0153_auto_20260130_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='primary_group',
            field=models.ForeignKey(blank=True, help_text='Primary role for the user (Owner, Director, Teacher, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='auth.group'),
        ),
    ]
