# Generated by Django 3.2.21 on 2026-02-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tottimeapp', '0154_mainuser_primary_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='qty3',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='qty4',
        ),
        migrations.RemoveField(
            model_name='amrecipe',
            name='qty5',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='qty3',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='qty4',
        ),
        migrations.RemoveField(
            model_name='breakfastrecipe',
            name='qty5',
        ),
        migrations.RemoveField(
            model_name='fruitrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='fruitrecipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='qty3',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='qty4',
        ),
        migrations.RemoveField(
            model_name='pmrecipe',
            name='qty5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qty3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qty4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qty5',
        ),
        migrations.RemoveField(
            model_name='vegrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='vegrecipe',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='wgrecipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='wgrecipe',
            name='qty1',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tottimeapp.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('percent_dv', models.CharField(blank=True, max_length=10)),
                ('raw_text', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
