# Generated by Django 3.2.21 on 2026-02-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0155_auto_20260211_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='breakfastrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fruitrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pmrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vegrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wgrecipe',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
