# Generated by Django 3.2.21 on 2026-02-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0156_auto_20260219_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='addfood',
            field=models.CharField(blank=True, help_text='Additional food for breakfast', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fluid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fruit_veg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('lunch', 'Lunch Recipe'), ('vegetable', 'Vegetable Recipe'), ('fruit', 'Fruit Recipe'), ('whole_grain', 'Whole Grain Recipe'), ('breakfast', 'Breakfast Recipe'), ('am_snack', 'AM Snack Recipe'), ('pm_snack', 'PM Snack Recipe'), ('am_pm_snack', 'AM and PM Snack Recipe')], default='lunch', help_text='Category of recipe', max_length=20),
        ),
    ]
