# Generated by Django 3.2.21 on 2026-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0157_auto_20260220_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='fruit_veg',
            new_name='fruit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='veg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
