# Generated by Django 3.2.21 on 2026-02-24 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0158_auto_20260220_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
