# Generated by Django 3.2.21 on 2026-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0159_mainuser_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='populate_am_snack',
            field=models.BooleanField(default=False, help_text='Can be used in AM snack menu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='populate_breakfast',
            field=models.BooleanField(default=False, help_text='Can be used in breakfast menu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='populate_lunch',
            field=models.BooleanField(default=False, help_text='Can be used in lunch menu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='populate_pm_snack',
            field=models.BooleanField(default=False, help_text='Can be used in PM snack menu'),
        ),
    ]
