# Generated by Django 3.2.21 on 2026-02-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0160_auto_20260225_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='standalone',
            field=models.BooleanField(default=False, help_text='Standalone ingredient rather than a full recipe'),
        ),
    ]
