# Generated by Django 3.2.21 on 2026-03-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0161_recipe_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='addfood_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_addfood_recipes', to='tottimeapp.rule'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fluid_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fluid_recipes', to='tottimeapp.rule'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fruit_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_recipes', to='tottimeapp.rule'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grain_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grain_recipes', to='tottimeapp.rule'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meat_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meat_recipes', to='tottimeapp.rule'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='veg_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veg_recipes', to='tottimeapp.rule'),
        ),
    ]
