# Generated by Django 3.2.21 on 2026-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0162_auto_20260302_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rule',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ignore_inventory',
            field=models.BooleanField(default=False, help_text='Ignore inventory tracking for this recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('lunch', 'Lunch Recipe'), ('vegetable', 'Vegetable Recipe'), ('fruit', 'Fruit Recipe'), ('whole_grain', 'Whole Grain Recipe'), ('breakfast', 'Breakfast Recipe'), ('am_snack', 'AM Snack Recipe'), ('pm_snack', 'PM Snack Recipe'), ('am_pm_snack', 'AM and PM Snack Recipe'), ('fluid', 'Fluid Recipe')], default='lunch', help_text='Category of recipe', max_length=20),
        ),
    ]
