# Generated by Django 3.2.21 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0163_auto_20260312_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_side_dish',
            field=models.BooleanField(default=False, help_text='Indicates if this item is a side dish'),
        ),
    ]
