# Generated by Django 3.2.21 on 2026-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0164_inventory_is_side_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='populate_am_snack',
            field=models.BooleanField(default=False, help_text='Can be used in AM snack menu'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='populate_breakfast',
            field=models.BooleanField(default=False, help_text='Can be used in breakfast menu'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='populate_lunch',
            field=models.BooleanField(default=False, help_text='Can be used in lunch menu'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='populate_pm_snack',
            field=models.BooleanField(default=False, help_text='Can be used in PM snack menu'),
        ),
    ]
