# Generated by Django 3.2.21 on 2026-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0165_auto_20260316_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='units',
        ),
        migrations.AddField(
            model_name='inventory',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('each', 'Each'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('g', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('slice', 'Slice'), ('loaf', 'Loaf'), ('pack', 'Pack'), ('case', 'Case')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='conversion_to_base',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many base units in one inventory unit (auto-set for simple units, user-set for custom packs)', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='custom_unit_label',
            field=models.CharField(blank=True, help_text="Optional: e.g., 'pack of 12 tacos', overrides default label", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many base units in one inventory unit (e.g., 12 for pack of 12, 1 for lb, etc.)', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('each', 'Each'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('g', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('slice', 'Slice'), ('loaf', 'Loaf'), ('pack', 'Pack'), ('case', 'Case')], max_length=20, null=True),
        ),
    ]
