# Generated by Django 3.2.21 on 2026-04-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0166_auto_20260331_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('each', 'Each'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('g', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('gal', 'Gallon (gal)'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('slice', 'Slice'), ('loaf', 'Loaf'), ('pack', 'Pack'), ('case', 'Case')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Portion size per student in base units', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('each', 'Each'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('g', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('gal', 'Gallon (gal)'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('slice', 'Slice'), ('loaf', 'Loaf'), ('pack', 'Pack'), ('case', 'Case')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RecipeSimilarityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive group name, e.g. "Fried Chicken Variants"', max_length=100)),
                ('recipes', models.ManyToManyField(blank=True, help_text='Recipes that cannot appear in the same week together', related_name='similarity_groups', to='tottimeapp.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
