# Generated by Django 3.2.21 on 2026-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0167_add_recipe_similarity_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
