# Generated by Django 3.2.21 on 2026-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0168_recipe_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='access_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
