# Generated by Django 3.2.21 on 2026-04-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0169_auto_20260423_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserBillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('square', 'Square'), ('stripe', 'Stripe'), ('manual', 'Manual')], default='square', max_length=20)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='inactive', max_length=20)),
                ('plan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('provider_customer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_checkout_id', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_location_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('billing_history', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Subscription',
                'verbose_name_plural': 'Billing Subscriptions',
            },
        ),
    ]
