# Generated by Django 3.2.21 on 2026-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0170_mainuserbillingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ignore_inventory',
            field=models.BooleanField(default=False, help_text='Ignore inventory tracking for this recipe'),
        ),
        migrations.AlterField(
            model_name='mainuserbillingsubscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='inactive', max_length=20),
        ),
    ]
