# Generated by Django 3.2.21 on 2026-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0171_auto_20260429_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='max_repetitions_week',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of repetitions per week'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='max_repetitions_week',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of repetitions per week'),
        ),
    ]
