# Generated by Django 3.2.21 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0172_auto_20260429_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many base units are in one pack/case/loaf (e.g., 20 slices per loaf)', max_digits=10),
        ),
    ]
