# Generated by Django 3.2.21 on 2026-06-04 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0174_alter_inventory_units_per_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast_1_2', models.PositiveIntegerField(default=0)),
                ('breakfast_3_5', models.PositiveIntegerField(default=0)),
                ('breakfast_6_12', models.PositiveIntegerField(default=0)),
                ('breakfast_13_18', models.PositiveIntegerField(default=0)),
                ('am_snack_1_2', models.PositiveIntegerField(default=0)),
                ('am_snack_3_5', models.PositiveIntegerField(default=0)),
                ('am_snack_6_12', models.PositiveIntegerField(default=0)),
                ('am_snack_13_18', models.PositiveIntegerField(default=0)),
                ('lunch_1_2', models.PositiveIntegerField(default=0)),
                ('lunch_3_5', models.PositiveIntegerField(default=0)),
                ('lunch_6_12', models.PositiveIntegerField(default=0)),
                ('lunch_13_18', models.PositiveIntegerField(default=0)),
                ('pm_snack_1_2', models.PositiveIntegerField(default=0)),
                ('pm_snack_3_5', models.PositiveIntegerField(default=0)),
                ('pm_snack_6_12', models.PositiveIntegerField(default=0)),
                ('pm_snack_13_18', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
