# Generated by Django 3.2.21 on 2026-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0175_dailymealcounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealcounts',
            name='am_snack_13_18',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='am_snack_1_2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='am_snack_3_5',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='am_snack_6_12',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='breakfast_13_18',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='breakfast_1_2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='breakfast_3_5',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='breakfast_6_12',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='lunch_13_18',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='lunch_1_2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='lunch_3_5',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='lunch_6_12',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='pm_snack_13_18',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='pm_snack_1_2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='pm_snack_3_5',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailymealcounts',
            name='pm_snack_6_12',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
