# Generated by Django 3.2.21 on 2026-06-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tottimeapp', '0176_auto_20260605_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('weekly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('schedule_json', models.JSONField(blank=True, help_text='Per-day/time codes, keyed by day->time->code', null=True)),
                ('time_begin', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=list, help_text='List of day keys e.g., ["mon","tue"]')),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitchen Time',
                'verbose_name_plural': 'Kitchen Times',
                'db_table': 'kitchentime',
                'ordering': ['-created_at'],
            },
        ),
    ]
