from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required  # Import login_required
from django.views.generic import RedirectView
from tottimeapp import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(views.index), name='index'),  
    path('index.html', login_required(views.index), name='index'),  
    path('index_director.html', login_required(views.index_director), name='index_director'),  
    path('index_teacher_parent.html', login_required(views.index_teacher_parent), name='index_teacher_parent'),  
    path('index_teacher.html', login_required(views.index_teacher), name='index_teacher'),  
    path('index_cook.html', login_required(views.index_cook), name='index_cook'),  
    path('index_parent.html', login_required(views.index_parent), name='index_parent'),  
    path('index_free_user.html', login_required(views.index_free_user), name='index_free_user'),  
    path('login/', views.user_login, name='login'),  # Unprotected view
    path('forgot-username/', views.forgot_username, name='forgot_username'),
    path('enrollment/', login_required(views.enrollment), name='enrollment'),
    path('enrollment/submission/<int:submission_id>/', login_required(views.enrollment_submission_detail), name='enrollment_submission_detail'),
    path('enrollment/public/<int:template_id>/', views.public_enrollment, name='public_enrollment'),
    path('enrollment/public/<int:template_id>/location/<int:location_id>/', views.public_enrollment, name='public_enrollment_with_location'),
    path('enrollment/success/', views.public_enrollment_success, name='public_enrollment_success'),
    path('enrollment/<int:template_id>/', views.public_enrollment, name='public_enrollment_with_template'),
    path('enrollment/location/<int:location_id>/', views.public_enrollment, name='public_enrollment_with_location'),
    path('enrollment/<int:template_id>/location/<int:location_id>/', views.public_enrollment, name='public_enrollment_full'),
    path('policies/', login_required(views.policies), name='policies'),
    path('send-public-enrollment-link/', login_required(views.send_public_enrollment_link), name='send_public_enrollment_link'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='tottimeapp/password_reset_form.html'
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='tottimeapp/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='tottimeapp/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='tottimeapp/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('signup/', views.user_signup, name='signup'),  # Unprotected view
    path('logout/', login_required(views.logout_view), name='logout'),  
    path('inventory/', login_required(views.inventory_list), name='inventory_list'),  
    path('app/', include('tottimeapp.urls')),  
    path('recipes/', login_required(views.recipes), name='recipes'),  
    path('rosters/', login_required(views.rosters), name='rosters'),  
    path('weekly-menu/', login_required(views.menu), name='menu'),  
    path('infant-menu/', login_required(views.infant_menu), name='infant_menu'),  
    path('menu_rules/', login_required(views.menu_rules), name='menu_rules'),
    path('add_rule/', login_required(views.add_rule), name='add_rule'),
    path('milk_count/', login_required(views.milk_count), name='milk_count'),  
    path('inventory/add/', login_required(views.add_item), name='add_item'),  
    path('edit_quantity/<int:item_id>/', login_required(views.edit_quantity), name='edit_quantity'),  
    path('remove_item/<int:item_id>/', login_required(views.remove_item), name='remove_item'),  
    path('api/out-of-stock-items/', login_required(views.get_out_of_stock_items), name='out_of_stock_items_api'),
    path('api/order-soon-items/', login_required(views.order_soon_items_view), name='order_soon_items'),  
    path('fetch-ingredients/', login_required(views.fetch_ingredients), name='fetch_ingredients'),  
    path('create-recipe/', login_required(views.create_recipe), name='create_recipe'),  
    path('create-fruit-recipe/', login_required(views.create_fruit_recipe), name='create_fruit_recipe'),
    path('create-veg-recipe/', login_required(views.create_veg_recipe), name='create_veg_recipe'),
    path('create-wg-recipe/', login_required(views.create_wg_recipe), name='create_wg_recipe'),
    path('fetch-recipes/', login_required(views.fetch_recipes), name='fetch_recipes'), 
    path('fetch-fruit-recipes/', login_required(views.fetch_fruit_recipes), name='fetch_fruit_recipes'),  
    path('fetch-veg-recipes/', login_required(views.fetch_veg_recipes), name='fetch_veg_recipes'),  
    path('fetch-wg-recipes/', login_required(views.fetch_wg_recipes), name='fetch_wg_recipes'),  
    path('fetch-rules/', login_required(views.fetch_rules), name='fetch_rules'),
    path('save-menu/', login_required(views.save_menu), name='save-menu'),  
    path('get-recipe/<int:recipe_id>/', login_required(views.get_recipe), name='get_recipe'),  
    path('delete-recipe/<str:category>/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('classroom_options/', login_required(views.classroom_options), name='classroom_options'),  
    path('classroom_options_teachers/', login_required(views.classroom_options_teachers), name='classroom_options_teachers'),  
    path('classroom_options_parents/', login_required(views.classroom_options_parents), name='classroom_options_parents'),  
    path('edit-teacher/<int:teacher_id>/', login_required(views.edit_teacher_info), name='edit_teacher'),
    path('edit-parent/<int:parent_id>/', login_required(views.edit_parent_info), name='edit_parent'),
    path('classroom_options_classrooms/', login_required(views.classroom_options_classrooms), name='classroom_options_classrooms'),  
    path('edit-classroom/<int:classroom_id>/', login_required(views.edit_classroom), name='edit_classroom'),
    path('add_classroom/', login_required(views.add_classroom), name='add_classroom'),
    path('delete_classroom/', login_required(views.delete_classroom), name='delete_classroom'),
    path('add_student/', login_required(views.add_student), name='add_student'),
    path('update_item_quantity/', login_required(views.update_item_quantity), name='update_item_quantity'),
    path('add-incident-report/', login_required(views.add_incident_report), name='add_incident_report'),
    path('incident-report-detail/', login_required(views.incident_report_detail), name='incident_report_detail'),
    path('add-diaper-change/', login_required(views.add_diaper_change), name='add_diaper_change'),
    path('diaper-changes-for-student/', login_required(views.diaper_changes_for_student), name='diaper_changes_for_student'),
    path('401/', login_required(views.error401), name='error401'),  
    path('404/', login_required(views.error404), name='error404'),  
    path('500/', login_required(views.error500), name='error500'),  
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('delete_request/', login_required(views.delete_request), name='delete_request'),  
    path('create-breakfast-recipe/', login_required(views.create_breakfast_recipe), name='create_breakfast_recipe'), 
    path('fetch-breakfast-recipes/', login_required(views.fetch_breakfast_recipes), name='fetch_breakfast_recipes'),  
    path('create-am-recipe/', login_required(views.create_am_recipe), name='create_am_recipe'),  
    path('fetch-am-recipes/', login_required(views.fetch_am_recipes), name='fetch_am_recipes'),  
    path('create-pm-recipe/', login_required(views.create_pm_recipe), name='create_pm_recipe'),  
    path('fetch-pm-recipes/', login_required(views.fetch_pm_recipes), name='fetch_pm_recipes'),  
    path('order-list/', login_required(views.order_list), name='order_list'), 
    path('api/shopping-list', login_required(views.shopping_list_api), name='shopping_list_api'), 
    path('update-orders/', login_required(views.update_orders), name='update_orders'), 
    path('delete-shopping-items/', login_required(views.delete_shopping_items), name='delete_shopping_items'),
    path('sign-in/', login_required(views.sign_in), name='sign_in'),
    path('process_code/', login_required(views.process_code), name='process_code'),
    path('daily-attendance/', login_required(views.daily_attendance), name='daily_attendance'),
    path('update_milk_count/', login_required(views.update_milk_count), name='update_milk_count'),
    path('milk-count/', login_required(views.milk_count_view), name='milk_count'),
    path('meal_count/', login_required(views.meal_count), name='meal_count'),
    path('generate_breakfast_menu/', login_required(views.generate_breakfast_menu), name='generate_breakfast_menu'),
    path('generate_pm_menu/', login_required(views.generate_pm_menu), name='generate_pm_menu'),
    path('generate_am_menu/', login_required(views.generate_am_menu), name='generate_am_menu'),
    path('generate_vegetable_menu/', login_required(views.generate_vegetable_menu), name='generate_vegetable_menu'),
    path('generate_fruit_menu/', login_required(views.generate_fruit_menu), name='generate_fruit_menu'),
    path('generate_menu/', login_required(views.generate_menu), name='generate_menu'),
    path('api/fruits/', login_required(views.get_fruits), name='get_fruits'),
    path('account_settings/', login_required(views.account_settings), name='account_settings'),
    path('api/save_menu/', login_required(views.save_menu), name='save_menu'),
    path('api/check_menu/', login_required(views.check_menu), name='check_menu'),
    path('past-menus/', login_required(views.past_menus), name='past_menus'),
    path('permissions/', login_required(views.permissions), name='permissions'),
    path('send-invitation/', login_required(views.send_invitation), name='send_invitation'),
    path('accept-invitation/<str:token>/', views.accept_invitation, name='accept_invitation'),
    path('invalid-invitation/', views.invalid_invitation, name='invalid_invitation'), 
    path('no_access/', login_required(views.no_access), name='no_access'),
    path('app_redirect/', login_required(views.app_redirect), name='app_redirect'),
    path('save_permissions/', login_required(views.save_permissions), name='save_permissions'),
    path('inbox/', login_required(views.inbox), name='message_inbox'), 
    path('conversation/<int:user_id>/', login_required(views.conversation), name='conversation'),
    path('start_conversation/<int:user_id>/', login_required(views.start_conversation), name='start_conversation'),
    path('payment/<int:subuser_id>/', login_required(views.payment_view), name='payment_detail'),
    path('payments/', login_required(views.payment_view), name='payment'),
    path('create-payment/', login_required(views.create_payment), name='create_payment'),
    path('create-payment-intent/', views.create_payment_intent, name='create_payment_intent'),
    path('update-payment-status/', views.update_payment_status, name='update_payment_status'),
    path('record-payment/', views.record_payment, name='record_payment'),
    path('record-payment/<int:subuser_id>/', views.record_payment, name='record_payment'),
    path('stripe/', login_required(views.stripe_login), name='stripe'),
    path("stripe/connect/", views.stripe_connect, name="stripe_connect"),
    path("stripe/callback/", views.stripe_callback, name="stripe_callback"),
    path('clock_in/', login_required(views.clock_in), name='clock_in'),
    path('process_teacher_code/', login_required(views.clock_in), name='process_teacher_code'),
    path('time-sheet/', login_required(views.time_sheet), name='time_sheet'),
    path('employee-detail/', login_required(views.employee_detail), name='employee_detail'),
    path('edit_time/', login_required(views.edit_time), name='edit_time'),
    path('delete-time/', login_required(views.delete_time), name='delete_time'),
    path('upload-profile-picture/', login_required(views.upload_profile_picture), name='upload_profile_picture'),
    path('update_attendance/', login_required(views.update_attendance), name='update_attendance'),
    path('manual-sign-in-ajax/', login_required(views.manual_sign_in_ajax), name='manual_sign_in_ajax'),
    path('delete_attendance/', login_required(views.delete_attendance), name='delete_attendance'),
    path("square/", login_required(views.square_account_view), name="square_account"),
    path("square/login/", views.square_login, name="square_login"),
    path("square/callback/", views.square_oauth_callback, name="square_callback"),
    path('square/oauth/callback/', views.square_oauth_callback, name='square_oauth_callback'),
    path('square/account/', views.square_account_view, name='square_account_view'),
    path('pay_summary/', login_required(views.pay_summary), name='pay_summary'),
    path('process_payment/', views.process_payment, name='process_payment'),
    path('add-tuition-plan/', login_required(views.add_tuition_plan), name='add_tuition_plan'),
    path('edit-tuition-plan/<int:plan_id>/', login_required(views.edit_tuition_plan), name='edit_tuition_plan'),
    path('pay_history/<int:subuser_id>/', login_required(views.pay_history), name='pay_history'),
    path('pay_history/', login_required(views.pay_history), name='pay_history'),
    path('all_pay_history/', login_required(views.all_pay_history), name='all_pay_history'),
    path('assign_teacher/', login_required(views.assign_teacher_to_classroom), name='assign_teacher_to_classroom'),
    path('unassign_teacher_from_classroom/', login_required(views.unassign_teacher_from_classroom), name='unassign_teacher_from_classroom'),
    path('classroom/', login_required(views.classroom), name='classroom'),
    path('attendance/<int:student_id>/', login_required(views.get_attendance_record), name='get_attendance_record'),
    path('update_classroom_attendance/', login_required(views.update_classroom_attendance), name='update_classroom_attendance'),
    path('edit-student/<int:student_id>/', login_required(views.edit_student_info), name='edit_student'),
    path('attendance_record/', login_required(views.attendance_record), name='attendance_record'),
    path('add-feed/', login_required(views.add_feed), name='add_feed'),
    path('feeds-for-student/', login_required(views.feeds_for_student), name='feeds_for_student'),
    path('update_attendance_times/', login_required(views.update_attendance_times), name='update_attendance_times'),
    path('inbox_perms/', login_required(views.inbox_perms), name='inbox_perms'),
    path('get-allowed-receivers/', login_required(views.get_allowed_receivers), name='get_allowed_receivers'),
    path('add-announcement/', login_required(views.add_announcement), name='add_announcement'),
    path('incident-report/sign/<int:report_id>/', login_required(views.sign_incident_report), name='sign_incident_report'),
    path('switch-account/', login_required(views.switch_account), name='switch_account'),
    path('api/update-shopping-item-status/', views.update_shopping_item_status, name='update_shopping_item_status'),
    path('api/delete-shopping-item/<int:item_id>/', views.delete_shopping_item, name='delete_shopping_item'),
    path('staff-orientation/', login_required(views.staff_orientation), name='staff_orientation'),
    path('staff-orientation/start/', login_required(views.start_orientation), name='start_orientation'),
    path('staff-orientation/update/<int:orientation_id>/<int:progress_id>/', login_required(views.update_progress), name='update_orientation_progress'),
    path('staff-orientation/delete/<int:orientation_id>/', login_required(views.delete_orientation), name='delete_orientation'),
    path('class-score/', login_required(views.class_score_form), name='class_score_form'),
    path('class-score/<int:sheet_id>/', login_required(views.view_score_sheet), name='view_score_sheet'),
    path('class-score/list/', login_required(views.score_sheet_list), name='score_sheet_list'),
    path('resources/', login_required(views.resources), name='resources'),
    path('resources/upload/', login_required(views.upload_resource), name='upload_resource'),
    path('resources/view/<int:resource_id>/', login_required(views.view_resource), name='view_resource'),
    path('resources/delete/<int:resource_id>/', login_required(views.delete_resource), name='delete_resource'),
    path('resource/sign/<uuid:uuid>/', views.public_resource_signature, name='public_resource_signature'),
    path('resource/confirmation/<uuid:uuid>/', views.signature_confirmation, name='signature_confirmation'),
    path('resources/send-signature-request/', views.send_signature_request, name='send_signature_request'),
    path('pdf-records/', login_required(views.pdf_records), name='pdf_records'),
    path('abc_quality/', login_required(views.abc_quality), name='abc_quality'),
    path('upload_documentation/', views.upload_documentation, name='upload_documentation'),
    path('compile-all-documents/', views.compile_all_documents, name='compile_all_documents'),
    # Survey management 
    path('surveys/', views.surveys_list, name='surveys_list'),
    path('surveys/create/', views.create_survey, name='create_survey'),
    path('surveys/<int:survey_id>/edit/', views.edit_survey, name='edit_survey'),
    path('surveys/<int:survey_id>/add-question/', views.add_question, name='add_question'),
    path('questions/<int:question_id>/edit/', views.edit_question, name='edit_question'),
    path('questions/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('survey/<int:survey_id>/send/', views.send_survey, name='send_survey'),
    path('survey/<int:survey_id>/results/', views.survey_results, name='survey_results'),
    path('surveys/<int:survey_id>/improvement-plan/create/', views.create_improvement_plan, name='create_improvement_plan'),
    path('improvement-plan/<int:plan_id>/edit/', views.edit_improvement_plan, name='edit_improvement_plan'),
    path('surveys/<int:survey_id>/delete/', views.delete_survey, name='delete_survey'),
    # Public survey taking
    path('surveys/<int:survey_id>/take/', views.take_survey, name='take_survey'),
    path('improvement-plan/<int:plan_id>/complete/', views.complete_improvement_plan, name='complete_improvement_plan'),
    # Public ABC Quality view
    path('abc-quality/public/<str:token>/', views.abc_quality_public, name='abc_quality_public'),
    path('create-public-link/', views.create_public_link, name='create_public_link'),
    path('api/indicator-link/<int:indicator_id>/', views.get_indicator_link, name='api_get_indicator_link'),
    path('api/save-indicator-link/', views.save_indicator_link, name='api_save_indicator_link'),
    path('api/remove-indicator-link/<int:indicator_id>/', views.remove_indicator_link, name='api_remove_indicator_link'),
    path('api/get-page-preview/<int:indicator_id>/', views.get_page_preview, name='get_page_preview'),
    path('proxy-page/', views.proxy_page, name='proxy_page'),
    path('create-public-link/', views.create_public_link, name='create_public_link'),
    path('abc-quality/', views.abc_quality, name='abc_quality'),
    path('abc-quality/public/<str:token>/', views.abc_quality_public, name='abc_quality_public'),
    path('public/<uuid:token>/', views.public_access_redirect, name='public_access'),
    path('api/get-indicator-link/<int:indicator_id>/', views.get_indicator_link, name='get_indicator_link'),
    #asq
    path('asq/', login_required(views.asq), name='asq'),
    path('asq_infant/', login_required(views.asq_infant), name='asq_infant'),
    #curriculum
    path('curriculum/', login_required(views.curriculum), name='curriculum'),
    path('curriculum/classroom/<int:classroom_id>/', login_required(views.classroom_themes), name='classroom_themes'),
    path('curriculum/theme/<int:theme_id>/add_activity/', views.add_activity, name='add_activity'),
    path('curriculum/activity/<int:activity_id>/upload_file/', views.upload_activity_file, name='upload_activity_file'),
    path('curriculum/theme/<int:theme_id>/<str:view_type>/', login_required(views.theme_activities), name='theme_activities'),
    path('curriculum/theme/<int:theme_id>/', login_required(views.theme_activities), name='theme_activities_default'),

    path('meal_calculator/', login_required(views.meal_calculator), name='meal_calculator'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Serve media files in development if DEBUG is True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)